name: Run Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.19]

    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
        terraform_wrapper: false

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --issues-exit-code=0 --timeout=5m

    - name: Run tests
      run: go test -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./... -v ./...

    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
